Add Contributor Name
bigredhacks/Registration-Site pull request #2
Opened 2023-11-01 22:19 UTC by LieselWong

2023-11-08 22:47 UTC, LieselWong commented
waaasup

2023-11-08 22:47 UTC, CollinWoo commented
asdfakljsdjlkadsl

2023-11-08 22:47 UTC, CollinWoo requested changes

2023-11-08 22:47 UTC, CollinWoo commented on README.md
> +- **Liesel Wong** - Software Member
I think Software Developer would be a more descriptive role name

2023-11-09 19:57 UTC, CollinWoo approved these changes
Welcome to the team! 🎉

2023-11-09 19:58 UTC, merged